export const basicDeck = {
  id: 1,
  name: 'basicDeck',
  cards: {
    clubA: {
      id: 1,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/blackA.png'),
      suit: 'club',
      title: 'clubA',
      value: 'A',
    },
    club2: {
      id: 2,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black2.png'),
      suit: 'club',
      title: 'club2',
      value: '2',
    },
    club3: {
      id: 3,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black3.jpg'),
      suit: 'club',
      title: 'club3',
      value: '3',
    },
    club4: {
      id: 4,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black4.jpg'),
      suit: 'club',
      title: 'club4',
      value: '4',
    },
    club5: {
      id: 5,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black5.png'),
      suit: 'club',
      title: 'club5',
      value: '5',
    },
    club6: {
      id: 6,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black6.png'),
      suit: 'club',
      title: 'club6',
      value: '6',
    },
    club7: {
      id: 7,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black7.jpg'),
      suit: 'club',
      title: 'club7',
      value: '7',
    },
    club8: {
      id: 8,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black8.png'),
      suit: 'club',
      title: 'club8',
      value: '8',
    },
    club9: {
      id: 9,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black9.png'),
      suit: 'club',
      title: 'club9',
      value: '9',
    },
    club10: {
      id: 10,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/black10.jpg'),
      suit: 'club',
      title: 'club10',
      value: '10',
    },
    clubJ: {
      id: 11,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/blackJ.jpg'),
      suit: 'club',
      title: 'clubJ',
      value: 'J',
    },
    clubQ: {
      id: 12,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/blackQ.png'),
      suit: 'club',
      title: 'clubQ',
      value: 'Q',
    },
    clubK: {
      id: 13,
      center: require('../assets/images/clubs.png'),
      cornerSuit: require('../assets/images/clubs.png'),
      cornerText: require('../assets/images/blackK.png'),
      suit: 'club',
      title: 'clubK',
      value: 'K',
    },
    diamondA: {
      id: 14,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/redA.png'),
      suit: 'diamond',
      title: 'diamondA',
      value: 'A',
    },
    diamond2: {
      id: 15,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red2.png'),
      suit: 'diamond',
      title: 'diamond2',
      value: '2',
    },
    diamond3: {
      id: 16,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red3.png'),
      suit: 'diamond',
      title: 'diamond3',
      value: '3',
    },
    diamond4: {
      id: 17,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red4.png'),
      suit: 'diamond',
      title: 'diamond4',
      value: '4',
    },
    diamond5: {
      id: 18,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red5.jpg'),
      suit: 'diamond',
      title: 'diamond5',
      value: '5',
    },
    diamond6: {
      id: 19,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red6.jpg'),
      suit: 'diamond',
      title: 'diamond6',
      value: '6',
    },
    diamond7: {
      id: 20,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red7.png'),
      suit: 'diamond',
      title: 'diamond7',
      value: '7',
    },
    diamond8: {
      id: 21,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red8.png'),
      suit: 'diamond',
      title: 'diamond8',
      value: '8',
    },
    diamond9: {
      id: 22,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red9.jpg'),
      suit: 'diamond',
      title: 'diamond9',
      value: '9',
    },
    diamond10: {
      id: 23,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/red10.png'),
      suit: 'diamond',
      title: 'diamond10',
      value: '10',
    },
    diamondJ: {
      id: 24,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/redJ.png'),
      suit: 'diamond',
      title: 'diamondJ',
      value: 'J',
    },
    diamondQ: {
      id: 25,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/redQ.png'),
      suit: 'diamond',
      title: 'diamondQ',
      value: 'Q',
    },
    diamondK: {
      id: 26,
      center: require('../assets/images/diamonds.png'),
      cornerSuit: require('../assets/images/diamonds.png'),
      cornerText: require('../assets/images/redK.png'),
      suit: 'diamond',
      title: 'diamondK',
      value: 'K',
    },
    heartA: {
      id: 27,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/redA.png'),
      suit: 'heart',
      title: 'heartA',
      value: 'A',
    },
    heart2: {
      id: 28,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red2.png'),
      suit: 'heart',
      title: 'heart2',
      value: '2',
    },
    heart3: {
      id: 29,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red3.png'),
      suit: 'heart',
      title: 'heart3',
      value: '3',
    },
    heart4: {
      id: 30,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red4.png'),
      suit: 'heart',
      title: 'heart4',
      value: '4',
    },
    heart5: {
      id: 31,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red5.jpg'),
      suit: 'heart',
      title: 'heart5',
      value: '5',
    },
    heart6: {
      id: 32,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red6.jpg'),
      suit: 'heart',
      title: 'heart6',
      value: '6',
    },
    heart7: {
      id: 33,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red7.png'),
      suit: 'heart',
      title: 'heart7',
      value: '7',
    },
    heart8: {
      id: 34,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red8.png'),
      suit: 'heart',
      title: 'heart8',
      value: '8',
    },
    heart9: {
      id: 35,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red9.jpg'),
      suit: 'heart',
      title: 'heart9',
      value: '9',
    },
    heart10: {
      id: 36,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/red10.png'),
      suit: 'heart',
      title: 'heart10',
      value: '10',
    },
    heartJ: {
      id: 37,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/redJ.png'),
      suit: 'heart',
      title: 'heartJ',
      value: 'J',
    },
    heartQ: {
      id: 38,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/redQ.png'),
      suit: 'heart',
      title: 'heartQ',
      value: 'Q',
    },
    heartK: {
      id: 39,
      center: require('../assets/images/hearts.png'),
      cornerSuit: require('../assets/images/hearts.png'),
      cornerText: require('../assets/images/redK.png'),
      suit: 'heart',
      title: 'heartK',
      value: 'K',
    },
    spadeA: {
      id: 40,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/blackA.png'),
      suit: 'spade',
      title: 'spadeA',
      value: 'A',
    },
    spade2: {
      id: 41,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black2.png'),
      suit: 'spade',
      title: 'spade2',
      value: '2',
    },
    spade3: {
      id: 42,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black3.jpg'),
      suit: 'spade',
      title: 'spade3',
      value: '3',
    },
    spade4: {
      id: 43,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black4.jpg'),
      suit: 'spade',
      title: 'spade4',
      value: '4',
    },
    spade5: {
      id: 44,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black5.png'),
      suit: 'spade',
      title: 'spade5',
      value: '5',
    },
    spade6: {
      id: 45,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black6.png'),
      suit: 'spade',
      title: 'spade6',
      value: '6',
    },
    spade7: {
      id: 46,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black7.jpg'),
      suit: 'spade',
      title: 'spade7',
      value: '7',
    },
    spade8: {
      id: 47,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black8.png'),
      suit: 'spade',
      title: 'spade8',
      value: '8',
    },
    spade9: {
      id: 48,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black9.png'),
      suit: 'spade',
      title: 'spade9',
      value: '9',
    },
    spade10: {
      id: 49,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/black10.jpg'),
      suit: 'spade',
      title: 'spade10',
      value: '10',
    },
    spadeJ: {
      id: 50,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/blackJ.jpg'),
      suit: 'spade',
      title: 'spadeJ',
      value: 'J',
    },
    spadeQ: {
      id: 51,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/blackQ.png'),
      suit: 'spade',
      title: 'spadeQ',
      value: 'Q',
    },
    spadeK: {
      id: 52,
      center: require('../assets/images/spades.png'),
      cornerSuit: require('../assets/images/spades.png'),
      cornerText: require('../assets/images/blackK.png'),
      suit: 'spade',
      title: 'spadeK',
      value: 'K',
    },
  },
};
